### ISSUE TITLE
"KeyError: 'puts'" while doing OptionChain('BAC') - works for other tickers 

### ISSUE THREAD

**Issue by DSA101** [makmac213/python-google-option-chain#1]
Hi - I am using OptionChain and it works OK for some tickers (e.g. 'AMAT', 'RCL'), but when I try to use 'BAC' or 'NYSE:BAC' it errors out as shown below. Google finance shows options for 'BAC' just fine.

Traceback (most recent call last):
  File "/home/sergei/workspace/Options/src/Options/main.py", line 49, in <module>
    oc = OptionChain(ticker)
  File "/usr/local/lib/python2.7/dist-packages/optionchain/core.py", line 42, in **init**
    puts += new_data['puts']
KeyError: 'puts'

**Comment by makmac213** [comment]
Thank you for checking, I tested and found out that this happen when there is an unequal number of puts to calls or vice versa. Updated the code to check if the key does not exist or is none value.

Thanks

**Comment by DSA101** [comment]
Mark - thanks for the fix! Sergei.
